### ISSUE TITLE
Can see the service starting up in the cli but cant access it through browser 

### ISSUE THREAD

**Issue by abhishekraghav** [gambol99/keycloak-proxy#251] opened 2017-07-13 22:58 UTC
i am using below config and could see the service listening at 127.0.0.1:3000 

docker run -p 3000:3000 quay.io/gambol99/keycloak-proxy:latest --listen=127.0.0.1:3000  --discovery-url=https://<my-keycloak-host>/auth/realms/<myrealm> --client-id=xyz --resources="uri=/*" --enable-logging=true --verbose=true --upstream-url=http://localhost:8080

When i open a browser an go to http://127.0.0.1:3000, i never gets redirected to anywhere and i see server not found. even though my keycloak-proxy service is up and running. **I may be not understanding how this keycloak-proxy.**
Please help me where i  am going wrong.

![image](https://user-images.githubusercontent.com/19988460/28191174-6c1309a2-684c-11e7-8b5b-2b9cf46c9eba.png)

**Comment by gambol99** [comment] 2017-07-14 09:22
hi @abhishekraghav ... this is [docker networking issue](https://forums.docker.com/t/using-localhost-for-to-access-running-container/3148/2), your listening on --listen 127.0.0.1:3000 and the ports aren't being forwarded ... you can --listen :3000

**Comment by abhishekraghav** [comment] 2017-07-14 15:27
Hey Thanks a lot. Now i am actually get to see some action.
This is my configuration i am passing
_docker run -p 3000:3000 quay.io/gambol99/keycloak-proxy:latest --listen=:3000 --discovery-url=https://<KeycloakServerURL>/auth/realms/DCI --client-id=safety --client-secret=977fc4ed-e2b0-485b-a398-be017b25e926 --resources="uri=/*|methods=GET" --enable-logging=true --verbose=true --upstream-url=http://localhost:8080/_

I am being redirected to keycloak once i try accessing  http://localhost:3000 and once i enter the users credentials, i am seeing a call being made to /oauth/callback and then i am locked in infinite loop. 

This is my log looks like:
<img width="1018" alt="3213232" src="https://user-images.githubusercontent.com/19988460/28218707-f955d0bc-68d6-11e7-81ce-a416c8f75e71.png">



Now I am successfully being redirected to keycloak after i am

**Comment by gambol99** [comment] 2017-07-14 17:59
hi @abhishekraghav .. the issue is caused by the proxy not listening on https. By default for security reasons the cookie is set [secure only](https://github.com/gambol99/keycloak-proxy/blob/master/cookies.go#L36), so your browser is wisely refusing to send the access token. 

Normally it will warn you of the configuration error [here](https://github.com/gambol99/keycloak-proxy/blob/master/config.go#L133-L135) but because you've not specified a --redirection-url  it doesn't know what the incoming protocol will be. This option is purposely left configurable as in our setup's we terminate TLS on the upstream proxy. But yes it should be documented better!!. 

In regard to fixing it for testing you can just override the setting via --secure-cookie=false or simply set the proxy to use TLS with --tls-cert and --tls-private-key

**Comment by gambol99** [comment] 2017-07-19 10:18
hi @abhishekraghav  ... did that solve the issue? ... can i close the issue

**Comment by abhishekraghav** [comment] 2017-07-19 13:05
Hey @gambol99 thanks a lot. Now i am not seeing the infinite loop issue. I think i am almost there.

There is one thing though,  i am not able to set the routings properly. I am trying to move away from keycloak-proxy and instead using your solution as it is more rich in features.

Here's my keycloak proxy config looks like:
{  
   "target-url":"http://<my-target-application-url>:8080",
   "bind-address":"0.0.0.0",
   "http-port":"8080",
   "applications":[  
      {  
         "base-path":"/",
         "error-page":"/error.html",
         "proxy-address-forwarding":true,
         "adapter-config":{  
            "realm":"sample",
            "auth-server-url":"https://<my-auth-server-url>/auth",
            "ssl-required":"external",
            "resource":"my-resourse-name",
            "public-client":true
         },
         "constraints":[  
            {  
               "pattern":"/protected/*",
               "authenticate":"true"
            },
            {  
               "pattern":"/ui/*",
               "permit":"true"
            }
         ]
      }
   ],
   "header-names":{  
      "keycloak-email":"mail"
   }
}

I just wanted to know, what should be corresponding config file for go-KCproxy looks like.
i tried this, i couldn't get it correct,

docker run -p 3000:3000 quay.io/gambol99/keycloak-proxy:latest --listen=:3000 --discovery-url=https://<my-auth-server-url>/auth/realms/sample --client-id=my-resourse-name --client-secret=977fc4-2b0-485b-a398-be017b25e926 --secure-cookie=false --redirection-url=http://localhost:3000  --resources="uri=/protected/*" --enable-logging=true  --verbose=true --upstream-url=http://<my-target-application-url>:8080

Am i missing anything here.

Thanks again.

**Comment by abhishekraghav** [comment] 2017-07-21 13:34
Hi @gambol99  any other information you need from my setup..??

**Comment by gambol99** [comment] 2017-07-21 21:26
hi @abhishekraghav .. what is the error your getting? as i'm not seeing anything unusual 

```shell
[jest@starfury keycloak-proxy]$ docker run -ti --rm quay.io/gambol99/keycloak-proxy:latest --version
keycloak-proxy version v2.1.0-rc2 (git+sha: ffe2fc4, built: 17-07-2017)
...
docker run --net=host quay.io/gambol99/keycloak-proxy:latest --listen=:3000 --discovery-url=<url> --client-id=broker --client-secret=<a secret> --redirection-url=http://127.0.0.1:3000 --resources="uri=/protected*" --enable-logging=true --verbose=true --upstream-url=http://127.0.0.1:8080 --secure-cookie=false

[jest@starfury]$ curl -k http://127.0.0.1:3000/test
dial tcp 127.0.0.1:8080: getsockopt: connection refused
[jest@starfury]$ curl -k http://127.0.0.1:3000/test

[jest@starfury]$ curl -k http://127.0.0.1:3000/protected
<a href="/oauth/authorize?state=L3Byb3RlY3RlZA==">Temporary Redirect</a>.
[jest@starfury]$ curl -k http://127.0.0.1:3000/protected/test
<a href="/oauth/authorize?state=L3Byb3RlY3RlZC90ZXN0">Temporary Redirect</a>.
[jest@starfury]$ curl -k http://127.0.0.1:3000/public/something
dial tcp 127.0.0.1:8080: getsockopt: connection refused

```

**Comment by abhishekraghav** [comment] 2017-07-22 12:35
Hey thanks.
Yes, its actually working. I have few doubts
is it possible to have redirects like this,
if i hit KeycloakProxyURL, i should be redirected to my UI compoment automatically. Currently i have to append /ui/ at the end of my keycloak proxy url (like this: localhost:3000/ui/) to redirect to my web component. 
i did configure my upstream url as like this:
--upstream-url=http://<my-web-component-url>:<port>/ui/

Still it redirects me to '/'.
There are other calls also which are made from ui. e.g. /protected which is working fine expected.

Thanks.

**Comment by gambol99** [comment] 2017-07-24 14:05
hi @abhishekraghav ... there isn't an option for a default redirect i'm afraid. At present, the proxy will keep the incoming url via state, perform the oauth flow and redirect back to the previous requested url, so if you come in via / it will redirect post auth. Since it's only /protected* which is authentication can you not place a redirect in the app? ... Also, note any uri added upstream-url would be ignored, the proxy only care's about the upstream host.

**Comment by abhishekraghav** [comment] 2017-07-27 05:32
Thanks for the explanation. Now i understood. 
One more question regarding injecting headers:
In keycloak proxy there is way to inject header like this and also you can override the header name in it e.g. 

   _"header-names":{  
      "keycloak-email":"mail"
   }_

In you version of keycloak proxy , what should be the corresponding way to achieve this. 
If i have to instruct KC proxy to inject user's email into the headers, what  should be the syntax..?
Is it possible to override the header name..? 
I found that there is something like this:
--headers value                     custom headers to the upstream request, key=value
I am little confused on what should be the key and what should be the value..?

PS: In keycloak i have created the mappers for adding user's email in access token and ID token.

**Comment by abhishekraghav** [comment] 2017-07-27 10:52
Also, I am little confused on how CORS can be enabled on KC proxy, i see way to add CORS header (Access-Control-Allow-Origin) header by passing this in the command line
_--cors-origins=[https://<my-keycloak-server-host>]_

But some how i am not seeing this header coming in the response from proxy in browser.
Am i doing something wrong..?

I see lot of other options to configure CORS related stuff e.g. --cors-methods, --cors-headers, --cors-exposed-headers,  --cors-max-age etc. Do i also need to pass these as well.

Also , how can i verify whether CORS header is added or not..?

Thanks.

**Comment by abhishekraghav** [comment] 2017-07-29 14:37
Hey @gambol99  i could successfully inject the header in the response. I get it finally by passing adding claims like this:
"add-claims": [
		"email"
	]
On my application, i could retrieve the same with this key , "X-Auth-Email". 👍 

Now the Only thing i am stuck now is the CORS Configuration.  Not really sure, how can i get that configured in my current setup. 

Pasting the configuration i tried:

```
{
	"discovery-url": "https://keycloak-example-url/auth/realms/SAMPLE",
	"client-id": "sample",
	"client-secret": "sample-secret",
	"listen": ":3000",
	"enable-refresh-token": true,
	"redirection-url": "http://localhost:3000/",
	"upstream-url": "http://my-app-url/appContext/",
	"secure-cookie": false,
	"enable-logging": true,
	"verbose": true,
	"resources": [
		{
			"uri": "/protected/*"
		}
	],
	"cors-origins": ["*"],
	"cors-headers": ["Access-Control-Allow-Origin","Access-Control-Allow-Headers"],
	"cors-methods": [],
	"cors-credentials": true,
	"cors-max-age": "1h",
	"cors-methods": [
		"GET",
		"POST",
		"HEAD",
		"OPTIONS"
	],
	"add-claims": [
		"email"
	]
}
```

Everything works fine as per above config, only the CORS part i am not getting it right. Please see if thats the right configuration. I should be seeing the CORS headers in the response headers in the reponse, but i couldn't see any such header in the browser.

I really appreciate your help.
Thanks a lot.

**Comment by abhishekraghav** [comment] 2017-07-30 12:41
Hey @gambol99  you can close this. I guess i should open a new issue/question for that as it is completely different from the original title of this issue/question. 
Thanks.

**Closed** 2017-08-02 22:29 UTC
Labels: question
