### ISSUE TITLE
keycloak-proxy hangs when misconfigured

### ISSUE THREAD

**Issue by timgent** [gambol99/keycloak-proxy#85] opened 2016-05-16 15:11 UTC
- I configured keycloak-proxy with the wrong config name: "upstream" instead of "upstream-url
- I ran the keycloak-proxy on a kubernetes cluster and it started up fine
- When I hit it with a request it crashes (crash look backoff)
- Nothing is logged

Few changes would be good:
- If mandatory configuration is missing the proxy shouldn't start and should log out an appropriate error
- The the proxy has issues when running it should log them out

**Comment by gambol99** [comment] 2016-05-16 22:21
I wasn't able to replicate this, but just checked the k8s RC for this and can see the problem. It's not a bug; by default if the upstream is not set, the default upstream is http://127.0.0.1:8081 (https://github.com/gambol99/keycloak-proxy/blob/master/config.go#L36), shown on command line;

```shell
--upstream-url "http://127.0.0.1:8081"						the url for the upstream endpoint you wish to proxy to [$PROXY_UPSTREAM_URL]
```

```YAML
  image: keycloak-proxy:v1.0.6
  imagePullPolicy: Always
  name: keycloak-proxy
  ports:
  - containerPort: 8081
    name: http
    protocol: TCP
  resources:
    limits:
      cpu: 250m
      memory: 256Mi 
```

It would effectively be forwarding to itself is a forever loop; with the hard limit on the container probably killing and causing the k8s 'crash loop backoff'

**Comment by timgent** [comment] 2016-05-17 12:16
Aha! Bad choice of port! That explains a lot thanks.

Obviously personal preference to some extent so feel free to ignore but I think mandating that configuration option is set may make sense, as I think very few people would leave the default, and having an error message may be more helpful than it proxying to the default.

**Comment by gambol99** [comment] 2016-05-17 12:22
yep ... make sense! .. i'll remove the default setting

**Comment by gambol99** [comment] 2016-05-17 12:46
will be part of 1.1.0 release ... https://github.com/gambol99/keycloak-proxy/pull/79/commits/4212cdb4397cd7e7b7e198a3a5d6022a124930cf

**Closed by gambol99** 2016-05-17 12:46 UTC
Labels: enhancement
